#!/bin/bash

LOG_FILE="${TRIM_PKGVAR}/info.log"
PID_FILE="${TRIM_PKGVAR}/app.pid"

# write the command to start your program here
CMD=""

log_msg() {
  echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >>${LOG_FILE}
}

start_process() {
  if status; then
    return 0
  fi

  log_msg "Starting process ..."
  [ -L "/usr/lib/udev/rules.d/50-usb-aic-net.rules" ] && rm -f "/usr/lib/udev/rules.d/50-usb-aic-net.rules"
  [ ! -L "/usr/lib/udev/rules.d/50-usb-aic-net.rules" ] && ln -s "${TRIM_APPDEST}/server/udev/50-usb-aic-net.rules" "/usr/lib/udev/rules.d/50-usb-aic-net.rules"
  udevadm control --reload-rules
  udevadm trigger

  [ -L "/lib/firmware/aic8800D80" ] && rm -f "/lib/firmware/aic8800D80"
  [ ! -L "/lib/firmware/aic8800D80" ] && ln -s "${TRIM_APPDEST}/server/fw/aic8800D80" "/lib/firmware/aic8800D80"

  insmod "${TRIM_APPDEST}/server/src/aic_load_fw/aic_load_fw.ko" >>${LOG_FILE} 2>&1
  insmod "${TRIM_APPDEST}/server/src/aic8800_fdrv/aic8800_fdrv.ko" >>${LOG_FILE} 2>&1
  return 0
}

stop_process() {
  log_msg "Stopping process ..."
  rmmod "${TRIM_APPDEST}/server/src/aic8800_fdrv/aic8800_fdrv.ko" >>${LOG_FILE} 2>&1
  rmmod "${TRIM_APPDEST}/server/src/aic_load_fw/aic_load_fw.ko" >>${LOG_FILE} 2>&1

  [ -L "/lib/firmware/aic8800D80" ] && rm -f "/lib/firmware/aic8800D80"

  [ -L "/usr/lib/udev/rules.d/50-usb-aic-net.rules" ] && rm -f "/usr/lib/udev/rules.d/50-usb-aic-net.rules"
  udevadm control --reload-rules
  udevadm trigger
  return 0
}

status() {
  lsmod | grep -q '^aic8800_fdrv\b' 2>/dev/null && lsmod | grep -q '^aic_load_fw\b' 2>/dev/null
  return $?
}

case $1 in
  start)
    # run start command. exit 0 if success, exit 1 if failed
    start_process
    ;;
  stop)
    # run stop command. exit 0 if success, exit 1 if failed
    stop_process
    ;;
  status)
    # check application status command. exit 0 if running, exit 3 if not running
    if status; then
      exit 0
    else
      exit 3
    fi
    ;;
  *)
    exit 1
    ;;
esac
