#!/bin/bash

### This script is called before the user installs the application.

OVS_BRIDGE="$(ovs-vsctl list-br 2>/dev/null | head -n 1)"
if [ -z "${OVS_BRIDGE}" ]; then
  echo "Please ensure that OVS bridges are present." >$TRIM_TEMP_LOGFILE
  exit 1
fi

if ! virsh -c qemu:///system capabilities | grep -q "qemu-system-aarch64"; then
  apt update
  apt install -y --no-install-recommends qemu-system-arm qemu-efi-aarch64
  [ $? -ne 0 ] && echo "Failed to install qemu packages." >$TRIM_TEMP_LOGFILE && exit 1
fi

exit 0
